// Code generated by protoc-gen-go. DO NOT EDIT.
// plugins:
// 	protoc-gen-go
// 	protoc
// source: temporal/api/stream/v1/message.proto

package stream

import (
	v1 "go.temporal.io/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          *v1.Payload            `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Metadata      map[string]*v1.Payload `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	TopicSequence int64                  `protobuf:"varint,4,opt,name=topic_sequence,json=topicSequence,proto3" json:"topic_sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessage) Reset() {
	*x = StreamMessage{}
	mi := &file_temporal_api_stream_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessage) ProtoMessage() {}

func (x *StreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_api_stream_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessage.ProtoReflect.Descriptor instead.
func (*StreamMessage) Descriptor() ([]byte, []int) {
	return file_temporal_api_stream_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *StreamMessage) GetBody() *v1.Payload {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *StreamMessage) GetMetadata() map[string]*v1.Payload {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *StreamMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *StreamMessage) GetTopicSequence() int64 {
	if x != nil {
		return x.TopicSequence
	}
	return 0
}

// A contiguous range of a stream delivered to a Workflow Task, along with the
// offsets it covers. The offsets are what History records; the messages
// themselves are never written to History.
type StreamSlice struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	StreamId string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	RunId    string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// Inclusive.
	FromOffset int64 `protobuf:"varint,3,opt,name=from_offset,json=fromOffset,proto3" json:"from_offset,omitempty"`
	// Exclusive. Equal to from_offset when the subscription observed nothing,
	// which is a fact replay has to reproduce rather than an absence of one.
	ToOffset      int64            `protobuf:"varint,4,opt,name=to_offset,json=toOffset,proto3" json:"to_offset,omitempty"`
	Messages      []*StreamMessage `protobuf:"bytes,5,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSlice) Reset() {
	*x = StreamSlice{}
	mi := &file_temporal_api_stream_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSlice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSlice) ProtoMessage() {}

func (x *StreamSlice) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_api_stream_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSlice.ProtoReflect.Descriptor instead.
func (*StreamSlice) Descriptor() ([]byte, []int) {
	return file_temporal_api_stream_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *StreamSlice) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *StreamSlice) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StreamSlice) GetFromOffset() int64 {
	if x != nil {
		return x.FromOffset
	}
	return 0
}

func (x *StreamSlice) GetToOffset() int64 {
	if x != nil {
		return x.ToOffset
	}
	return 0
}

func (x *StreamSlice) GetMessages() []*StreamMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

// The offsets a Workflow Task consumed, without the payloads. Recorded on
// WorkflowTaskCompleted so History grows with Workflow Tasks rather than with
// messages.
type StreamCursor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	FromOffset    int64                  `protobuf:"varint,2,opt,name=from_offset,json=fromOffset,proto3" json:"from_offset,omitempty"`
	ToOffset      int64                  `protobuf:"varint,3,opt,name=to_offset,json=toOffset,proto3" json:"to_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamCursor) Reset() {
	*x = StreamCursor{}
	mi := &file_temporal_api_stream_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamCursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamCursor) ProtoMessage() {}

func (x *StreamCursor) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_api_stream_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamCursor.ProtoReflect.Descriptor instead.
func (*StreamCursor) Descriptor() ([]byte, []int) {
	return file_temporal_api_stream_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *StreamCursor) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *StreamCursor) GetFromOffset() int64 {
	if x != nil {
		return x.FromOffset
	}
	return 0
}

func (x *StreamCursor) GetToOffset() int64 {
	if x != nil {
		return x.ToOffset
	}
	return 0
}

var File_temporal_api_stream_v1_message_proto protoreflect.FileDescriptor

const file_temporal_api_stream_v1_message_proto_rawDesc = "" +
	"\n" +
	"$temporal/api/stream/v1/message.proto\x12\x16temporal.api.stream.v1\x1a$temporal/api/common/v1/message.proto\"\xb0\x02\n" +
	"\rStreamMessage\x123\n" +
	"\x04body\x18\x01 \x01(\v2\x1f.temporal.api.common.v1.PayloadR\x04body\x12O\n" +
	"\bmetadata\x18\x02 \x03(\v23.temporal.api.stream.v1.StreamMessage.MetadataEntryR\bmetadata\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12%\n" +
	"\x0etopic_sequence\x18\x04 \x01(\x03R\rtopicSequence\x1a\\\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.temporal.api.common.v1.PayloadR\x05value:\x028\x01\"\xc2\x01\n" +
	"\vStreamSlice\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1f\n" +
	"\vfrom_offset\x18\x03 \x01(\x03R\n" +
	"fromOffset\x12\x1b\n" +
	"\tto_offset\x18\x04 \x01(\x03R\btoOffset\x12A\n" +
	"\bmessages\x18\x05 \x03(\v2%.temporal.api.stream.v1.StreamMessageR\bmessages\"i\n" +
	"\fStreamCursor\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x1f\n" +
	"\vfrom_offset\x18\x02 \x01(\x03R\n" +
	"fromOffset\x12\x1b\n" +
	"\tto_offset\x18\x03 \x01(\x03R\btoOffsetB\x89\x01\n" +
	"\x19io.temporal.api.stream.v1B\fMessageProtoP\x01Z#go.temporal.io/api/stream/v1;stream\xaa\x02\x18Temporalio.Api.Stream.V1\xea\x02\x1bTemporalio::Api::Stream::V1b\x06proto3"

var (
	file_temporal_api_stream_v1_message_proto_rawDescOnce sync.Once
	file_temporal_api_stream_v1_message_proto_rawDescData []byte
)

func file_temporal_api_stream_v1_message_proto_rawDescGZIP() []byte {
	file_temporal_api_stream_v1_message_proto_rawDescOnce.Do(func() {
		file_temporal_api_stream_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_temporal_api_stream_v1_message_proto_rawDesc), len(file_temporal_api_stream_v1_message_proto_rawDesc)))
	})
	return file_temporal_api_stream_v1_message_proto_rawDescData
}

var file_temporal_api_stream_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_temporal_api_stream_v1_message_proto_goTypes = []any{
	(*StreamMessage)(nil), // 0: temporal.api.stream.v1.StreamMessage
	(*StreamSlice)(nil),   // 1: temporal.api.stream.v1.StreamSlice
	(*StreamCursor)(nil),  // 2: temporal.api.stream.v1.StreamCursor
	nil,                   // 3: temporal.api.stream.v1.StreamMessage.MetadataEntry
	(*v1.Payload)(nil),    // 4: temporal.api.common.v1.Payload
}
var file_temporal_api_stream_v1_message_proto_depIdxs = []int32{
	4, // 0: temporal.api.stream.v1.StreamMessage.body:type_name -> temporal.api.common.v1.Payload
	3, // 1: temporal.api.stream.v1.StreamMessage.metadata:type_name -> temporal.api.stream.v1.StreamMessage.MetadataEntry
	0, // 2: temporal.api.stream.v1.StreamSlice.messages:type_name -> temporal.api.stream.v1.StreamMessage
	4, // 3: temporal.api.stream.v1.StreamMessage.MetadataEntry.value:type_name -> temporal.api.common.v1.Payload
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_temporal_api_stream_v1_message_proto_init() }
func file_temporal_api_stream_v1_message_proto_init() {
	if File_temporal_api_stream_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_temporal_api_stream_v1_message_proto_rawDesc), len(file_temporal_api_stream_v1_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_temporal_api_stream_v1_message_proto_goTypes,
		DependencyIndexes: file_temporal_api_stream_v1_message_proto_depIdxs,
		MessageInfos:      file_temporal_api_stream_v1_message_proto_msgTypes,
	}.Build()
	File_temporal_api_stream_v1_message_proto = out.File
	file_temporal_api_stream_v1_message_proto_goTypes = nil
	file_temporal_api_stream_v1_message_proto_depIdxs = nil
}
