// Code generated by protoc-gen-go-helpers. DO NOT EDIT.
package stream

import (
	"google.golang.org/protobuf/proto"
)

// Marshal an object of type StreamMessage to the protobuf v3 wire format
func (val *StreamMessage) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type StreamMessage from the protobuf v3 wire format
func (val *StreamMessage) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *StreamMessage) Size() int {
	return proto.Size(val)
}

// Equal returns whether two StreamMessage values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *StreamMessage) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *StreamMessage
	switch t := that.(type) {
	case *StreamMessage:
		that1 = t
	case StreamMessage:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type StreamSlice to the protobuf v3 wire format
func (val *StreamSlice) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type StreamSlice from the protobuf v3 wire format
func (val *StreamSlice) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *StreamSlice) Size() int {
	return proto.Size(val)
}

// Equal returns whether two StreamSlice values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *StreamSlice) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *StreamSlice
	switch t := that.(type) {
	case *StreamSlice:
		that1 = t
	case StreamSlice:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type StreamCursor to the protobuf v3 wire format
func (val *StreamCursor) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type StreamCursor from the protobuf v3 wire format
func (val *StreamCursor) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *StreamCursor) Size() int {
	return proto.Size(val)
}

// Equal returns whether two StreamCursor values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *StreamCursor) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *StreamCursor
	switch t := that.(type) {
	case *StreamCursor:
		that1 = t
	case StreamCursor:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}
