// Code generated by protoc-gen-go-helpers. DO NOT EDIT.
package stream

import (
	"fmt"

	"google.golang.org/protobuf/proto"
)

// Marshal an object of type StreamRecord to the protobuf v3 wire format
func (val *StreamRecord) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type StreamRecord from the protobuf v3 wire format
func (val *StreamRecord) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *StreamRecord) Size() int {
	return proto.Size(val)
}

// Equal returns whether two StreamRecord values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *StreamRecord) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *StreamRecord
	switch t := that.(type) {
	case *StreamRecord:
		that1 = t
	case StreamRecord:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type StreamSlice to the protobuf v3 wire format
func (val *StreamSlice) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type StreamSlice from the protobuf v3 wire format
func (val *StreamSlice) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *StreamSlice) Size() int {
	return proto.Size(val)
}

// Equal returns whether two StreamSlice values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *StreamSlice) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *StreamSlice
	switch t := that.(type) {
	case *StreamSlice:
		that1 = t
	case StreamSlice:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type StreamRange to the protobuf v3 wire format
func (val *StreamRange) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type StreamRange from the protobuf v3 wire format
func (val *StreamRange) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *StreamRange) Size() int {
	return proto.Size(val)
}

// Equal returns whether two StreamRange values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *StreamRange) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *StreamRange
	switch t := that.(type) {
	case *StreamRange:
		that1 = t
	case StreamRange:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

var (
	StreamRecordKind_shorthandValue = map[string]int32{
		"Unspecified": 0,
		"Data":        1,
		"Finish":      2,
	}
)

// StreamRecordKindFromString parses a StreamRecordKind value from  either the protojson
// canonical SCREAMING_CASE enum or the traditional temporal PascalCase enum to StreamRecordKind
func StreamRecordKindFromString(s string) (StreamRecordKind, error) {
	if v, ok := StreamRecordKind_value[s]; ok {
		return StreamRecordKind(v), nil
	} else if v, ok := StreamRecordKind_shorthandValue[s]; ok {
		return StreamRecordKind(v), nil
	}
	return StreamRecordKind(0), fmt.Errorf("%s is not a valid StreamRecordKind", s)
}
