// Code generated by protoc-gen-go. DO NOT EDIT.
// plugins:
// 	protoc-gen-go
// 	protoc
// source: temporal/api/stream/v1/message.proto

package stream

import (
	reflect "reflect"
	"strconv"
	sync "sync"
	unsafe "unsafe"

	v1 "go.temporal.io/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// What a record means to a reader. Kept on the record itself so every store
// and every language reads it the same way without a private envelope.
type StreamRecordKind int32

const (
	// Read as DATA.
	STREAM_RECORD_KIND_UNSPECIFIED StreamRecordKind = 0
	// A value the producer published; `body` carries it.
	STREAM_RECORD_KIND_DATA StreamRecordKind = 1
	// The producer named by `producer_id` writes nothing more on `topic`.
	// Says nothing about that producer's outcome and does not end the stream.
	STREAM_RECORD_KIND_FINISH StreamRecordKind = 2
)

// Enum value maps for StreamRecordKind.
var (
	StreamRecordKind_name = map[int32]string{
		0: "STREAM_RECORD_KIND_UNSPECIFIED",
		1: "STREAM_RECORD_KIND_DATA",
		2: "STREAM_RECORD_KIND_FINISH",
	}
	StreamRecordKind_value = map[string]int32{
		"STREAM_RECORD_KIND_UNSPECIFIED": 0,
		"STREAM_RECORD_KIND_DATA":        1,
		"STREAM_RECORD_KIND_FINISH":      2,
	}
)

func (x StreamRecordKind) Enum() *StreamRecordKind {
	p := new(StreamRecordKind)
	*p = x
	return p
}

func (x StreamRecordKind) String() string {
	switch x {
	case STREAM_RECORD_KIND_UNSPECIFIED:
		return "Unspecified"
	case STREAM_RECORD_KIND_DATA:
		return "Data"
	case STREAM_RECORD_KIND_FINISH:
		return "Finish"
	default:
		return strconv.Itoa(int(x))
	}

}

func (StreamRecordKind) Descriptor() protoreflect.EnumDescriptor {
	return file_temporal_api_stream_v1_message_proto_enumTypes[0].Descriptor()
}

func (StreamRecordKind) Type() protoreflect.EnumType {
	return &file_temporal_api_stream_v1_message_proto_enumTypes[0]
}

func (x StreamRecordKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamRecordKind.Descriptor instead.
func (StreamRecordKind) EnumDescriptor() ([]byte, []int) {
	return file_temporal_api_stream_v1_message_proto_rawDescGZIP(), []int{0}
}

// One entry in a stream. The record is the wire format: stores keep it
// serialized as is and readers in every language decode the same bytes.
type StreamRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The value the producer published, stored as sent. A stream provider
	// writes and reads it as part of the record, so applying a payload codec
	// to it is the provider's job.
	Body *v1.Payload `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	// Producer-supplied provenance, stored as sent.
	Metadata map[string]*v1.Payload `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Producer-supplied grouping label, stored as sent.
	Topic string `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	// How to read this record. Unspecified is read as DATA.
	Kind StreamRecordKind `protobuf:"varint,4,opt,name=kind,proto3,enum=temporal.api.stream.v1.StreamRecordKind" json:"kind,omitempty"`
	// Who wrote the record. Empty when the owning Workflow did.
	ProducerId string `protobuf:"bytes,5,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	// The producer's attempt. Readers treat a later attempt by the same
	// producer as superseding what the earlier one wrote.
	Attempt int64 `protobuf:"varint,6,opt,name=attempt,proto3" json:"attempt,omitempty"`
	// The producer's position within its attempt, zero when it does not number
	// its records. Stored as sent; the server does not assign, validate or
	// order by it, and the stream's own offsets are what order a read.
	Sequence      int64 `protobuf:"varint,7,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRecord) Reset() {
	*x = StreamRecord{}
	mi := &file_temporal_api_stream_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRecord) ProtoMessage() {}

func (x *StreamRecord) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_api_stream_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRecord.ProtoReflect.Descriptor instead.
func (*StreamRecord) Descriptor() ([]byte, []int) {
	return file_temporal_api_stream_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRecord) GetBody() *v1.Payload {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *StreamRecord) GetMetadata() map[string]*v1.Payload {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *StreamRecord) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *StreamRecord) GetKind() StreamRecordKind {
	if x != nil {
		return x.Kind
	}
	return STREAM_RECORD_KIND_UNSPECIFIED
}

func (x *StreamRecord) GetProducerId() string {
	if x != nil {
		return x.ProducerId
	}
	return ""
}

func (x *StreamRecord) GetAttempt() int64 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *StreamRecord) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

var File_temporal_api_stream_v1_message_proto protoreflect.FileDescriptor

const file_temporal_api_stream_v1_message_proto_rawDesc = "" +
	"\n" +
	"$temporal/api/stream/v1/message.proto\x12\x16temporal.api.stream.v1\x1a$temporal/api/common/v1/message.proto\"\x9c\x03\n" +
	"\fStreamRecord\x123\n" +
	"\x04body\x18\x01 \x01(\v2\x1f.temporal.api.common.v1.PayloadR\x04body\x12N\n" +
	"\bmetadata\x18\x02 \x03(\v22.temporal.api.stream.v1.StreamRecord.MetadataEntryR\bmetadata\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12<\n" +
	"\x04kind\x18\x04 \x01(\x0e2(.temporal.api.stream.v1.StreamRecordKindR\x04kind\x12\x1f\n" +
	"\vproducer_id\x18\x05 \x01(\tR\n" +
	"producerId\x12\x18\n" +
	"\aattempt\x18\x06 \x01(\x03R\aattempt\x12\x1a\n" +
	"\bsequence\x18\a \x01(\x03R\bsequence\x1a\\\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.temporal.api.common.v1.PayloadR\x05value:\x028\x01*r\n" +
	"\x10StreamRecordKind\x12\"\n" +
	"\x1eSTREAM_RECORD_KIND_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17STREAM_RECORD_KIND_DATA\x10\x01\x12\x1d\n" +
	"\x19STREAM_RECORD_KIND_FINISH\x10\x02B\x89\x01\n" +
	"\x19io.temporal.api.stream.v1B\fMessageProtoP\x01Z#go.temporal.io/api/stream/v1;stream\xaa\x02\x18Temporalio.Api.Stream.V1\xea\x02\x1bTemporalio::Api::Stream::V1b\x06proto3"

var (
	file_temporal_api_stream_v1_message_proto_rawDescOnce sync.Once
	file_temporal_api_stream_v1_message_proto_rawDescData []byte
)

func file_temporal_api_stream_v1_message_proto_rawDescGZIP() []byte {
	file_temporal_api_stream_v1_message_proto_rawDescOnce.Do(func() {
		file_temporal_api_stream_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_temporal_api_stream_v1_message_proto_rawDesc), len(file_temporal_api_stream_v1_message_proto_rawDesc)))
	})
	return file_temporal_api_stream_v1_message_proto_rawDescData
}

var file_temporal_api_stream_v1_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_temporal_api_stream_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_temporal_api_stream_v1_message_proto_goTypes = []any{
	(StreamRecordKind)(0), // 0: temporal.api.stream.v1.StreamRecordKind
	(*StreamRecord)(nil),  // 1: temporal.api.stream.v1.StreamRecord
	nil,                   // 2: temporal.api.stream.v1.StreamRecord.MetadataEntry
	(*v1.Payload)(nil),    // 3: temporal.api.common.v1.Payload
}
var file_temporal_api_stream_v1_message_proto_depIdxs = []int32{
	3, // 0: temporal.api.stream.v1.StreamRecord.body:type_name -> temporal.api.common.v1.Payload
	2, // 1: temporal.api.stream.v1.StreamRecord.metadata:type_name -> temporal.api.stream.v1.StreamRecord.MetadataEntry
	0, // 2: temporal.api.stream.v1.StreamRecord.kind:type_name -> temporal.api.stream.v1.StreamRecordKind
	3, // 3: temporal.api.stream.v1.StreamRecord.MetadataEntry.value:type_name -> temporal.api.common.v1.Payload
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_temporal_api_stream_v1_message_proto_init() }
func file_temporal_api_stream_v1_message_proto_init() {
	if File_temporal_api_stream_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_temporal_api_stream_v1_message_proto_rawDesc), len(file_temporal_api_stream_v1_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_temporal_api_stream_v1_message_proto_goTypes,
		DependencyIndexes: file_temporal_api_stream_v1_message_proto_depIdxs,
		EnumInfos:         file_temporal_api_stream_v1_message_proto_enumTypes,
		MessageInfos:      file_temporal_api_stream_v1_message_proto_msgTypes,
	}.Build()
	File_temporal_api_stream_v1_message_proto = out.File
	file_temporal_api_stream_v1_message_proto_goTypes = nil
	file_temporal_api_stream_v1_message_proto_depIdxs = nil
}
