// Code generated by protoc-gen-go-helpers. DO NOT EDIT.
package notification

import (
	"google.golang.org/protobuf/proto"
)

// Marshal an object of type Notification to the protobuf v3 wire format
func (val *Notification) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type Notification from the protobuf v3 wire format
func (val *Notification) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *Notification) Size() int {
	return proto.Size(val)
}

// Equal returns whether two Notification values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *Notification) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *Notification
	switch t := that.(type) {
	case *Notification:
		that1 = t
	case Notification:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type ChannelListener to the protobuf v3 wire format
func (val *ChannelListener) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type ChannelListener from the protobuf v3 wire format
func (val *ChannelListener) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *ChannelListener) Size() int {
	return proto.Size(val)
}

// Equal returns whether two ChannelListener values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *ChannelListener) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *ChannelListener
	switch t := that.(type) {
	case *ChannelListener:
		that1 = t
	case ChannelListener:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type WorkflowListener to the protobuf v3 wire format
func (val *WorkflowListener) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type WorkflowListener from the protobuf v3 wire format
func (val *WorkflowListener) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *WorkflowListener) Size() int {
	return proto.Size(val)
}

// Equal returns whether two WorkflowListener values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *WorkflowListener) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *WorkflowListener
	switch t := that.(type) {
	case *WorkflowListener:
		that1 = t
	case WorkflowListener:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}
