// Code generated by protoc-gen-go. DO NOT EDIT.
// plugins:
// 	protoc-gen-go
// 	protoc
// source: temporal/api/notification/v1/message.proto

package notification

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	v1 "go.temporal.io/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A notification tells the listeners of a channel that a source they consume
// has moved. It is not data: the listener reads the source itself. A channel
// is named by the writer and its listeners; for a stream, the provider formats
// the stream's identity into the name. Writers never learn who listens. The
// server folds notifications per listener while one is pending and no task has
// been scheduled for it, keeping the one with the highest counter.
type Notification struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The channel the writer notified. Listeners register on the same name.
	Channel string `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	// Where the source stands after the write that caused this notification,
	// in the writer's terms. Opaque to the server.
	Position []byte `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	// Orders notifications from one channel's writers. The writer derives it
	// from the position, since only the source can order its positions. Among
	// notifications folded together, the one with the highest counter is kept.
	Counter int64 `protobuf:"varint,3,opt,name=counter,proto3" json:"counter,omitempty"`
	// Details for the listener, such as which topic moved. Bounded in size and
	// carried as payloads, so a codec applies as to any payload.
	Metadata      map[string]*v1.Payload `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_temporal_api_notification_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_api_notification_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_temporal_api_notification_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Notification) GetPosition() []byte {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Notification) GetCounter() int64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *Notification) GetMetadata() map[string]*v1.Payload {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// A listener of a channel: a Workflow Execution woken with a Workflow Task, or
// a callback the server invokes with each notification.
type ChannelListener struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Assigned by the server when the listener registers.
	ListenerId string `protobuf:"bytes,1,opt,name=listener_id,json=listenerId,proto3" json:"listener_id,omitempty"`
	// Types that are valid to be assigned to Listener:
	//
	//	*ChannelListener_Workflow
	//	*ChannelListener_Callback
	Listener       isChannelListener_Listener `protobuf_oneof:"listener"`
	RegisteredTime *timestamppb.Timestamp     `protobuf:"bytes,4,opt,name=registered_time,json=registeredTime,proto3" json:"registered_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChannelListener) Reset() {
	*x = ChannelListener{}
	mi := &file_temporal_api_notification_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelListener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelListener) ProtoMessage() {}

func (x *ChannelListener) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_api_notification_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelListener.ProtoReflect.Descriptor instead.
func (*ChannelListener) Descriptor() ([]byte, []int) {
	return file_temporal_api_notification_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *ChannelListener) GetListenerId() string {
	if x != nil {
		return x.ListenerId
	}
	return ""
}

func (x *ChannelListener) GetListener() isChannelListener_Listener {
	if x != nil {
		return x.Listener
	}
	return nil
}

func (x *ChannelListener) GetWorkflow() *WorkflowListener {
	if x != nil {
		if x, ok := x.Listener.(*ChannelListener_Workflow); ok {
			return x.Workflow
		}
	}
	return nil
}

func (x *ChannelListener) GetCallback() *v1.Callback {
	if x != nil {
		if x, ok := x.Listener.(*ChannelListener_Callback); ok {
			return x.Callback
		}
	}
	return nil
}

func (x *ChannelListener) GetRegisteredTime() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredTime
	}
	return nil
}

type isChannelListener_Listener interface {
	isChannelListener_Listener()
}

type ChannelListener_Workflow struct {
	Workflow *WorkflowListener `protobuf:"bytes,2,opt,name=workflow,proto3,oneof"`
}

type ChannelListener_Callback struct {
	Callback *v1.Callback `protobuf:"bytes,3,opt,name=callback,proto3,oneof"`
}

func (*ChannelListener_Workflow) isChannelListener_Listener() {}

func (*ChannelListener_Callback) isChannelListener_Listener() {}

// A Workflow Execution listening on a channel.
type WorkflowListener struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	// The run that subscribed. The server follows a continue-as-new to the
	// chain's current run when it delivers.
	RunId         string `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowListener) Reset() {
	*x = WorkflowListener{}
	mi := &file_temporal_api_notification_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowListener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowListener) ProtoMessage() {}

func (x *WorkflowListener) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_api_notification_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowListener.ProtoReflect.Descriptor instead.
func (*WorkflowListener) Descriptor() ([]byte, []int) {
	return file_temporal_api_notification_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *WorkflowListener) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *WorkflowListener) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

var File_temporal_api_notification_v1_message_proto protoreflect.FileDescriptor

const file_temporal_api_notification_v1_message_proto_rawDesc = "" +
	"\n" +
	"*temporal/api/notification/v1/message.proto\x12\x1ctemporal.api.notification.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a$temporal/api/common/v1/message.proto\"\x92\x02\n" +
	"\fNotification\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\fR\bposition\x12\x18\n" +
	"\acounter\x18\x03 \x01(\x03R\acounter\x12T\n" +
	"\bmetadata\x18\x04 \x03(\v28.temporal.api.notification.v1.Notification.MetadataEntryR\bmetadata\x1a\\\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.temporal.api.common.v1.PayloadR\x05value:\x028\x01\"\x91\x02\n" +
	"\x0fChannelListener\x12\x1f\n" +
	"\vlistener_id\x18\x01 \x01(\tR\n" +
	"listenerId\x12L\n" +
	"\bworkflow\x18\x02 \x01(\v2..temporal.api.notification.v1.WorkflowListenerH\x00R\bworkflow\x12>\n" +
	"\bcallback\x18\x03 \x01(\v2 .temporal.api.common.v1.CallbackH\x00R\bcallback\x12C\n" +
	"\x0fregistered_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0eregisteredTimeB\n" +
	"\n" +
	"\blistener\"J\n" +
	"\x10WorkflowListener\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runIdB\xa7\x01\n" +
	"\x1fio.temporal.api.notification.v1B\fMessageProtoP\x01Z/go.temporal.io/api/notification/v1;notification\xaa\x02\x1eTemporalio.Api.Notification.V1\xea\x02!Temporalio::Api::Notification::V1b\x06proto3"

var (
	file_temporal_api_notification_v1_message_proto_rawDescOnce sync.Once
	file_temporal_api_notification_v1_message_proto_rawDescData []byte
)

func file_temporal_api_notification_v1_message_proto_rawDescGZIP() []byte {
	file_temporal_api_notification_v1_message_proto_rawDescOnce.Do(func() {
		file_temporal_api_notification_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_temporal_api_notification_v1_message_proto_rawDesc), len(file_temporal_api_notification_v1_message_proto_rawDesc)))
	})
	return file_temporal_api_notification_v1_message_proto_rawDescData
}

var file_temporal_api_notification_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_temporal_api_notification_v1_message_proto_goTypes = []any{
	(*Notification)(nil),          // 0: temporal.api.notification.v1.Notification
	(*ChannelListener)(nil),       // 1: temporal.api.notification.v1.ChannelListener
	(*WorkflowListener)(nil),      // 2: temporal.api.notification.v1.WorkflowListener
	nil,                           // 3: temporal.api.notification.v1.Notification.MetadataEntry
	(*v1.Callback)(nil),           // 4: temporal.api.common.v1.Callback
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*v1.Payload)(nil),            // 6: temporal.api.common.v1.Payload
}
var file_temporal_api_notification_v1_message_proto_depIdxs = []int32{
	3, // 0: temporal.api.notification.v1.Notification.metadata:type_name -> temporal.api.notification.v1.Notification.MetadataEntry
	2, // 1: temporal.api.notification.v1.ChannelListener.workflow:type_name -> temporal.api.notification.v1.WorkflowListener
	4, // 2: temporal.api.notification.v1.ChannelListener.callback:type_name -> temporal.api.common.v1.Callback
	5, // 3: temporal.api.notification.v1.ChannelListener.registered_time:type_name -> google.protobuf.Timestamp
	6, // 4: temporal.api.notification.v1.Notification.MetadataEntry.value:type_name -> temporal.api.common.v1.Payload
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_temporal_api_notification_v1_message_proto_init() }
func file_temporal_api_notification_v1_message_proto_init() {
	if File_temporal_api_notification_v1_message_proto != nil {
		return
	}
	file_temporal_api_notification_v1_message_proto_msgTypes[1].OneofWrappers = []any{
		(*ChannelListener_Workflow)(nil),
		(*ChannelListener_Callback)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_temporal_api_notification_v1_message_proto_rawDesc), len(file_temporal_api_notification_v1_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_temporal_api_notification_v1_message_proto_goTypes,
		DependencyIndexes: file_temporal_api_notification_v1_message_proto_depIdxs,
		MessageInfos:      file_temporal_api_notification_v1_message_proto_msgTypes,
	}.Build()
	File_temporal_api_notification_v1_message_proto = out.File
	file_temporal_api_notification_v1_message_proto_goTypes = nil
	file_temporal_api_notification_v1_message_proto_depIdxs = nil
}
